### ISSUE TITLE
Netcat or similar tools to check/test network connectivity

### ISSUE THREAD

**Issue by eriweb** [NuxRo/macchinina#1]
When testing port forwarding/load balancing and similar it's very handy to have the possibility to listen on (or connect to) ports for traffic.

Would it be possible to include netcat, or similar tool?

Source: http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/nc/

**Comment by NuxRo** [comment]
I'll have a look at including that. BTW tcpdump and telnet are included, which may help you.

**Comment by NuxRo** [comment]
Netcat (nc) added to busybox, template rebuilt. Please test and let me know if it works as expected.
